# -*- coding: utf-8 -*-
"""practice2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vadEH4tEP-p2P4nbmQXMDsMXR3dWb9Yl
"""



"""1. Write a program to access the third element from the given list.
Input: [10, 20, 30, 40, 50]
Output: 30
"""

my_list = [10,20,30,40,50]
print(my_list[2])

"""2 .Write a program to extract the first three elements from the given list.
Input: [100, 200, 300, 400, 500, 600]
Output: [100, 200, 300]

"""

my_list= [100,200,300,400,500,600]
print(my_list[:3])

"""3. Write a program to extract elements from index 2 to 5 from the given list.
Input: [11, 22, 33, 44, 55, 66, 77]
Output: [33, 44, 55, 66]


"""

my_list = [11,22,33,44,55,66,77]
print(my_list[2:6])

"""4 . Write a program to extract the last element from the last nested list.
Input: [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
Output: i

"""

my_list = [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]

print(my_list[-1][-1])

"""5. Write a program to append a string "Hello" to the given list.
Input: ['apple', 'banana', 'cherry']
Output: ['apple', 'banana', 'cherry', 'Hello'
"""

my_list = ['apple','banana','cherry']
my_list.append("hello")
print(my_list)

"""6. Write a program to append a list [5, 6, 7] as a single element in the given list.
Input: [1, 2, 3, 4]
Output: [1, 2, 3, 4, [5, 6, 7]]
"""

my_list = [1,2,3,4]
my_list.append([5,6,7])
print(my_list)

"""7. Write a program to remove the first element from the given list using the pop function.
Input: [100, 200, 300, 400]
Output: [200, 300, 400]

"""

my_list = [100,200,300,400]
my_list.pop(0)
print(my_list)

"""8.  Write a program to remove the number 5 from the given list if it exists.
Input: [1, 2, 3, 4, 5, 6]
Output: [1, 2, 3, 4, 6]
"""

my_list = [1,2,3,4,5,6]
my_list.remove(5)
print(my_list)