# -*- coding: utf-8 -*-
"""practice 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AkK7v1ss8Pg3NmkoNzERFPfE3uURknn
"""



"""1. Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you access the element 15 using positive indexing? Write a Python program to achieve this.

"""

my_tuple = (5,10,15,20,25)
print(my_tuple[2])

"""2. Given a tuple my_tuple = (100, 200, 300, 400, 500), how can you access the element 300 using negative indexing? Write a Python program to achieve this."""

my_tuple = (100,200,300,400,500)
print(my_tuple[-3])

"""3. Given a tuple my_tuple = (1, 2, 3, (4, 5, 6)), how can you access the element 6 from the nested tuple using indexing? Write a Python program to achieve this.

"""

my_tuple = (1,2,3,(4,5,6))
print(my_tuple[3][2])

"""4. Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you slice it to obtain (10, 15, 20)? Write a Python program to achieve this.

"""

my_tuple = (5,10,15,20,25)
result = my_tuple[1:4]
print(result)

"""5. Given a tuple my_tuple = ('Python', 'Java', 'C++', 'JavaScript'), how can you access the last element without knowing its index? Write a Python program to achieve this.

"""

my_tuple = ('Python', 'Java', 'C++', 'JavaScript')
print(my_tuple[-1])

"""6. Given two tuples tuple1 = (1, 2, 3) and tuple2 = (4, 5, 6), how can you concatenate them into a single tuple? Write a Python program to achieve this."""

tuple1 = (1,2,3)
tuple2 = (4,5,6)
result = tuple1 + tuple2
print(result)

"""7. Given a tuple my_tuple = ('x', 'y', 'z', 'a'), how can you check if the element 'y' exists in the tuple? Write a Python program to achieve this.

"""

my_tuple = ('x', 'y', 'z', 'a')

if 'y' in my_tuple:
    print("y exists in the tuple")
else:
    print("y does not exist in the tuple")

"""8.Given a tuple my_tuple = ('apple', 'banana', 'apple', 'cherry', 'apple'), how can you count the number of occurrences of 'apple'? Write a Python program to achieve this.

"""

my_tuple = ('apple','banana','apple','cherry','apple')
count = my_tuple.count('apple')
print(count)

"""9.Given a tuple my_tuple = (True, False, True, False), how can you find the number of True values in the tuple? Write a Python program to achieve this.

"""

my_tuple = (True,False,True,False)
count = my_tuple.count(True)
print(count)

"""10.Given a tuple my_tuple = ('Python', 3.8, True, (1, 2, 3)), how can you access the nested tuple (1, 2, 3)? Write a Python program to achieve this.

"""

my_tuple = ('Python', 3.8, True, (1, 2, 3))
print(my_tuple[3])

"""11. Given a tuple my_tuple = (10, 20, 30), how can you convert it into a list? Write a Python program to achieve this.

"""

my_tuple = (10,20,30)
my_list = list(my_tuple)
print(my_list)

12. Given a tuple my_tuple = (7, 14, 21, 28, 35), how can you find the smallest and largest elements? Write a Python program to achieve this.

my_tuple = (7,14,21,28,35)
smallest = min(my_tuple)
largest = max(my_tuple)
print("smallest element :",smallest)
print("largest element :",largest)

"""13.Given a tuple my_tuple = (2, 4, 6, 8, 10), how can you find the sum of all elements? Write a Python program to achieve this.

"""

my_tuple = (2,4,6,8,10)
total = sum(my_tuple)
print("sum of all elements:",total)

"""14. Given a tuple my_tuple = ('a', 'b', 'c', 'd'), how can you reverse the order of elements? Write a Python program to achieve this.

"""

my_tuple = ('a', 'b', 'c', 'd')

reversed_tuple = my_tuple[::-1]

print(reversed_tuple)

"""15. Given two tuples tuple1 = (1, 2, 3) and tuple2 = (1, 2, 3), how can you check if they are equal? Write a Python program to achieve this.

"""

tuple1 = (1,2,3)
tuple2 = (1,2,3)
if tuple1 == tuple2 :
  print("They are equal ")
else:
  print("They are not equal ")

"""16. 	Given a tuple my_tuple = (10, 20, 30, 40), how can you unpack its values into separate variables? Write a Python program to achieve this.

"""

my_tuple = (10,20,30,40)
a, b, c, d = my_tuple
print(a)
print(b)
print(c)
print(d)

"""17. Given a tuple my_tuple = (3, 6, 9, 12, 15), how can you convert it into a string? Write a Python program to achieve this."""

my_tuple = (3,3,9,12,15)
my_string = str(my_tuple)
print(my_string)

"""18. Given a tuple my_tuple = (1, 2, 3, 4, 5), how can you iterate through it using a for loop? Write a Python program to achieve this.

"""

my_tuple = (1, 2, 3, 4, 5)

for element in my_tuple:
    print(element)

"""19 . Given a tuple my_tuple = (100, 200, 300, 400), how can you convert it into a dictionary with keys as index positions? Write a Python program to achieve this.

"""

my_tuple = (100,200,300,400)
my_dict = dict(enumerate(my_tuple))
print(my_dict)

"""20. Given a tuple my_tuple = (1, 2, 3, 4, 5), how can you delete the entire tuple? Write a Python program to achieve this.


"""

my_tuple = (1,2,3,4,5)
del my_tuple
print("tuple deleted successfully")