# -*- coding: utf-8 -*-
"""Python_Practice_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dijWOOrSWQ52MZq9XzGlwAmwfLP0EvfZ
"""

a = int(input("Enter a first num :"))
b = int(input("Enter a second num :"))
Sum = a + b
print("Sum =",Sum)

"""2 . Calculate and print the midpoint of two numbers entered by the user."""

a = int(input("Enter a first num : "))
b = int(input("Enter a second num : "))
Mid = a + b /2
print("Mid = ",Mid)

"""3 Write a Python program to calculate the area of a triangle using the formula: area = 0.5 * base * height."""

Base = int(input("Enter a triangle Base : "))
Height = int(input("Enter a triangle Height : "))
area = 0.5 * Height + Base
print ("area =",area)

"""4 . Take three numbers as input from the user and display their product."""

a = int(input("Enter a first num : "))
b = int(input("Enter a second num : "))
c = int(input("Enter a third num : "))
product = a * b * c
print ("product = ",product)

"""5 . Take a number as input and display its square and cube."""

a = int(input("Enter a num : "))
squre = a * a
cube = a * a * a
print("squre =",squre)
print("cube =",cube)

"""6 . Take two numbers as input and display their quotient and remainder."""

a = int(input("Enter a first num : "))
b = int(input("Enter a second num : "))
quotient = a // b
remainder = a % b
print("quotient =",quotient)
print("remainder =",remainder)

"""7.	Take three numbers as input and display their average."""

a = int(input("Enter a first num : "))
b = int(input("Enter a second num : "))
c = int(input("Enter a third num : "))
avg = a + b + c / 3
print("avg =", avg)

"""8.	Write a Python program to calculate the area of a rectangle using the formula: area = length * width."""

length = int(input("Enter rectangle length: "))
width = int(input("Enter rectangle width: "))

area = length * width

print("Area =", area)

"""9 . Take five numbers as input representing marks obtained and total marks."""

num1 = int(input("Enter a Num1 marks : "))
num2 = int(input("Enter a num2 marks : "))
num3 = int(input("Enter a num3 marks : "))
num4 = int(input("Enter a num4 marks : "))
num5 = int(input("Enter a num5 marks : "))
tmarks= num1 + num2 + num3 + num4 + num5
percentage = tmarks / 5
print ("tmarks =", tmarks)
print ("percentage = ",percentage)

"""10. Write a Python program to swap two numbers entered by the user without using a third variable.


"""

a = int(input("Enter a first num : "))
b = int(input("Enter a second num : "))
a , b = b , a
print("After sorting : ")
print ("Enter first num : ", a)
print("Enter second num : ",b)

"""11 . Take a number as input and check whether it is even or odd.

"""

a = int(input("Enter a num : "))
if a % 2 == 0:
  print("Even ")
else :
  print("odd")

""" 12 .Write a Python program to convert temperature from Celsius to Fahrenheit using the formula: F = (C × 9/5) + 32."""

cel = float(input("Enter  temp in cel : "))
f = (cel * 9/5)+ 32
print("f= ",f)

"""13 . Write a Python program to convert temperature from Fahrenheit to Celsius using the formula: C = (F - 32) × 5/9."""

f = float(input("Enter a fahrenheit to celsius : "))
c = (f - 32) * 5/9
print("c = ",c)

"""14.	Take two numbers as input and find their greatest common divisor (GCD)."""

a = int(input("Enter a num1 : "))
b = int(input("Enter a num2 : "))
while b != 0 :
  rem = a % b
  a = b
  b = rem
print("GCD = ", a)

"""15.	Write a Python program to calculate the simple interest using the formula: SI = (P × R × T) / 100, where P is the principal amount, R is the rate of interest, and T is the time in years.

"""

P = int(input("Enter a principle amount : "))
R = int(input("Enter a Rate of interest : "))
T = int(input("Enter a Time in years : "))
SI = (P * R * T)/ 100
print ("SI = ",SI)

"""16 . Write a Python program to check whether a number is positive, negative, or zero."""

num = int(input("Enter a num : "))
if num > 0:
  print("Positive ")
elif num < 0:
  print("Negative")
else :
  print ("zero ")

"""17 . Write a Python program to find the largest among three numbers entered by the user."""

num1 = int(input("Enter a num1 : "))
num2 = int(input("Enter a num2 : "))
num3 = int(input("Enter a num3 : "))
if num1 >= num2 and num1 >= num3 :
  print ("num1")
elif num2 >= num3 and num2 >= num1:
  print("num2")
else :
  print("num3")

""" 18 .Take a number as input and check whether it is a multiple of 5."""

num = int(input("Enter a num : "))
if num % 5 == 0 :
  print("Num div by 5")
else:
  print("Num not div by 5 ")

"""19 .Write a Python program to calculate the perimeter of a circle using the formula: perimeter = 2 * π * radius."""

import math
radius = int(input("Enter a circle radius : "))
perimeter = 2 * 3.14 * radius
print("perimeter =",perimeter)

"""20 . Write a Python program to check whether a number is divisible by both 3 and 5.

"""

num = int(input("Enter a num : "))
if num % 3 == 0 and num % 5 == 0 :
  print("Num div by 3 and 5 ")
else :
  print("Num not div by 3 and 5")